---
title: "SDS 192 Mini-Project 3 Contributions"
subtitle: "SDS 192"
author: 
- name: Aaliyah Viera
  affiliation: Smith College
- name: Rose Ordonez-Rodriguez
  affiliation: Smith College
- name: Nancy Jimenez
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
source:
  mode: editor
output: 
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---


# Aaliyah Viera

  Aaliyah dedicated most of her time working on the function part of the project, creating the question we are trying to answer with the function and getting it to work appropriately. Attended both Professor’s office hours and the Spinelli Center to look over this code and aspect. Additionally, she worked on pivoting our data set from the first section in Office Hours with Rose and Nancy. She has also helped Rose in perfecting the first map by adding a second variable that measures chemical release.


# Rose Ordonez-Rodriguez

  Despite the challenges of Rose not having a viable computer as hers broke, eventually she was able to find a replacement and get started on the code for our first map. Additionally, she consulted with the Spinelli Center with the rest of the group members to resolve GitHub issues. Rose was also able to attend Professor Lindsay’s office hours individually to get further assistance on map 1’s code to easily run, get answers to our follow up questions created during class, and guidance for the structuring to the rest of our project. Alongside Aaliyah and Nancy, Rose was able to complete her portion on the blog post to ensure the final part of the project was complete.


# Nancy Jimenez

  Along with helping Aaliyah with the pivot, Nancy mapped the last three maps showing the specific locations of facilities who were releasing specific chemicals. Also pushed the contributions, standards, and blog posts from the main branch. 

