---
title: "SDS 192 Group Contract"
author:
 - Aaliyah Viera
 - Rose Ordonez-Rodriguez
 - Nancy Jiminez Sandoval
date: "Last updated on `r Sys.Date()`"
output: html_document
---

Working in groups can be both incredibly rewarding and incredibly challenging. The most effective collaborations explicitly outline group roles, expectations, and procedures in advance to coordinate how the group will operate, to establish mechanisms of accountability, and to mitigate the risk of conflict. It is important that, throughout the semester, you address group concerns as they come up. This may involve assigning someone to check in with team members that are falling behind, establishing expectations for attending office hours and asking for help, calling team meetings to discuss issues, or reaching out to the instructor to resolve enduring and unresolved conflicts.		

# ROLES

## Who will be responsible for scheduling meetings and hosting Zoom calls? 

Aaliyah 

## Who will be responsible for facilitating discussion during team meetings?

Aaliyah

## Who will be responsible for taking notes and recording decisions during meetings?

All

## Who will be responsible for emailing the professor with questions?

Aaliyah

## Who will be responsible for requesting group assignment extensions?

Rose

## Who will be responsible for setting deadlines for drafts? 

All

## Who will be responsible for checking in with team members when drafts are late?

All of us

## Who will be responsible for reviewing all materials before submission?

All

## Who will be responsible for submitting assignments?

All


# COLLABORATIVE WORKSPACES

## Where will the team keep meeting notes? 

Google docs

## Where will the team store drafts of assignments? 

google docs

## Through what channels will the team communicate when not meeting?

Slack. imessage

## What is the expected response time for emails and messages? 

ASAP


# MEETINGS

## How often will the team meet? 

1-2 TIMES A WEEK

## What days/times will the team meet?

TUESDAYS 4-5PM 
WEDNESDAYS 7-9PM
FRIDAYS 1:30-2:30PM

## How long will meetings be?

1-2 HOURS 

## How will you make decisions during meetings (e.g. consensus, a vote)?

CONSENSUS
		
## What strategies will you use to stay on task during meetings?

ASSIGNING TASKS TO EACH OF US TO LOOK OVER

## How should team members inform each other if they are going to be late to a meeting?

A QUICK TEXT
			
## When is it ok for a team member to skip a meeting? How soon should they inform the group?

SICKNESS, EMERGENCY, AS SOON AS THEY KNOW

## What will you do if a group member is chronically absent from or late to meetings?

Checking in and rescheudling 

## What will you do if a group member is consistently not participating in meetings?

checking in and encouraging to attempt a current issue 

## What are your expectations for respectful engagement and communication during meetings and in collaborative workspaces? What will you do if a member of your team does not meet these expectations?

Listetening in to what others have to say, respecting the space for others

# ASSIGNMENTS

## How will you ensure that all team members fully understand assignment expectations? What will you do if your team is unsure how to complete an assignment?

Look for resources and build of each other

## How will you ensure that all team members are contributing equitably to assignments?

Making sure tasks assignments are equal and redistributing tasks

## How soon in advance of deadlines do you expect all team members to share drafts of their work?

2 days in advance.

## What will be your process for reviewing each other’s work before submission?

looking at each others code; pushing it and review 

## What will you do if the quality of a team member’s work does not meet the group’s expectations? When is it permissible to revise another team member’s work?

Just ask beforehand for revision and you can make suggestions (making comments in google docs)

## What are your expectations around punctuality regarding group deadlines? How should team members inform each other if they need an extension?

just warning in imessage (24 hour turn around)

## What will you do if a student is consistently late in submitting draft work?

checking in

## What will you do if you discover that a team member’s work violates the Academic Code of Conduct?

Warning them that it does and suggesting to fix it 

# SIGNATURES

* I participated in drafting the standards, roles, and procedures outlined in this document.
* I agree to abide by the terms and conditions outlined in this document.			
* I understand that failing to abide by the terms and conditions outlined in this document may impact my grade.
 							
Signature: Aaliyah Viera 
Date: `r format(Sys.time(), '%d %B, %Y')`

Signature: Nancy Jimenez
Date: `r format(Sys.time(), '%d %B, %Y')`

Signature: Rose Ordonez-Rodriguez
Date `r format(Sys.time(), '%d %B, %Y')`


Once you are done, in the Git tab in your Environment pane, stage and commit your changes, and then push them to your GitHub repo.  

