---
title: "SDS 192 Mini-Project 3 Standards"
subtitle: "SDS 192"
author: 
- name: Aaliyah Viera
  affiliation: Smith College
- name: Rose Ordonez-Rodriguez
  affiliation: Smith College
- name: Nancy Jimenez
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
source:
  mode: editor
output: 
  html_document:
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---


# Tidying Data

To demonstrate an ability to import local data: In our first code chunk, we imported our two data sets, tri dallas texas data and dallas texas redlining data.

To demonstrate an ability to mutate across multiple columns:
(converting from grams to pounds) Also in our first code chunk, we use the mutate function on dallas_texas_tri to convert all the units of measurements from grams to pounds. 

To demonstrate an ability to perform a pivot:
in our pivot, we are moving stack air, fugitive air, and water into one column and renaming it "Type_of_Release". After converting all release measurements into a uniform measurement form, we pivoted to transfer it all into one new column titled "Values_Pounds". Performing this pivot allowed us to wrangle the data ease, getting our release information in a more efficient way. 


# Programming in R

To Demonstrate an ability to write a custom function:
we wrote a function with one argument being factory_name that is able to list the top ten facilities that release the most chemicals and the type of release that they are mainly emitting.

To demonstrate an ability to iterate a function over multiple values in a vector:
we converted the top ten factory names into a vector then used a map function to iterate the factory_name function argument over the top ten factories. This function makes a ggplot for every factory that is listed in the top ten. This allows us to see what type of air release (stack, water, or fugitive) is most prevalent when it comes to chemical releases when mapping onto redlining data. 

To demonstrate an ability to discern different data object types in R:
We used polygon mapping on our first map to help see the grades of redlining in Dallas County and added markers to discern type of release and total amount of chemical releases. Vectors were used in the function in order to iterate through a list of values in our map function.


# Mapping

To demonstrates an ability to produce point and/or polygon-based maps with descriptive title and labels:
We made all of our maps with the redlining shape file for Dallas Texas. Using this data set, we made the first layer for all of our maps showing the redlines areas and the different grades in each area, with a legend: D = "hazardous," C = "definitely declining," B = "still desirable" and A = "best". Using the cross-referencing skill learned in SDS 100, we were able to assign captions to each visualization, as well as hyperlinks throughout the blog post. 

To demonstrate an ability to transform data to an appropriate CRS
We made sure to convert the CRS for our TRI data to 4269 in order to align them, this ensured leaflet would process the data we wanted onto the map. 

To demonstrate an ability to create informative color palettes for points or polygons on a map:
In each map we incorporated a polygon map pertaining to the redlining areas within Dallas County, the color palette "YlOrRd" allowed us to show the different grades of redlining present in 2021. Additionally, we added a "Greens" palette for the points that layered over the polygon map to emphasize the concentration and amount of chemical releases.
 


> Please be sure that all files are rendered to HTML and that you have checked the output prior to submission!









